---
# Supported options: 
#   sn-nature:       Style for submissions to Nature Portfolio journals
#   sn-basic:        Basic Springer Nature Reference Style/Chemistry Reference Style
#   sn-mathphys:     Math and Physical Sciences Reference Style
#   sn-aps:          American Physical Society (APS) Reference Style
#   sn-vancouver:    Vancouver Reference Style
#   sn-apa:          APA Reference Style 
#   sn-chicago:      Chicago-based Humanities Reference Style
#   default:         Default

classoptions: 
  - sn-vancouver      
  - Numbered      # Optional: Use numbered references instead of namedate references (only for sn-nature, sn-basic, sn-vancouver, sn-chicago, sn-mathphys or sn-nature)
  # - referee       # Optional: Use double line spacing 
  # - lineno        # Optional: Add line numbers
  # - iicol         # Optional: Double column layour

title: "`r params$X@title_1L_chr`" 
titlerunning: Mapping psychological measures to health utility

# authors:

authors: 
  - firstname: Matthew
    particle: P 
    lastname: Hamilton
    email: matthew.hamilton1@monash.edu
    affiliation: [2,1]
    corresponding: TRUE
  # - prefix: Mr.
    #suffix: III
    #naturename: Poet Laureate
    # degrees: MSc #, PhD
    equalcont: These authors contributed equally to this work.
    
  - firstname: Caroline
    lastname: Gao
    #     email: caroline.gao@orygen.org.au
    affiliation: [2,3,1]
    equalcont: These authors contributed equally to this work.

  - firstname: Kate  
    particle: M
    lastname: Filia
    #     email: kate.filia@orygen.org.au
    affiliation: [2,3]

  - firstname: Jana
    particle: M
    lastname: Menssink
    #     email: jana.menssink@orygen.org.au
    affiliation: [2,3]

  - firstname: Sonia
    #particle: M
    lastname: Sharmin
    #     email: jana.menssink@orygen.org.au
    affiliation: [2,3]

  - firstname: Nic
    #particle: M
    lastname: Telford
    #     email: jana.menssink@orygen.org.au
    affiliation: [4]

  - firstname: Helen
    #particle: M
    lastname: Herrman
    #     email: jana.menssink@orygen.org.au
    affiliation: [2,3]

  - firstname: Ian
    particle: B
    lastname: Hickie
    #     email: jana.menssink@orygen.org.au
    affiliation: [5]

  - firstname: Cathrine
    lastname: Mihalopoulos
    #     email: cathy.mihalopoulos@deakin.edu.au
    affiliation: [1]  

  - firstname: Debra
    particle: J
    lastname: Rickwood
    #     email: jana.menssink@orygen.org.au
    affiliation: [4,6]
    
  - firstname: Patrick 
    particle: D 
    lastname: McGorry
    #     email: pat.mcgorry@orygen.org.au
    affiliation: [2,3]

  - firstname: Sue
    particle: M
    lastname: Cotton
    #     email: sue.cotton@orygen.org.au
    affiliation: [2,3]
    
affiliations:
  - number: 1
    corresponding: TRUE
    info:
      orgdiv: School of Public Health and Preventive Medicine
      orgname: Monash University
    address:
        #street: "553 St Kilda Road"
        city: Melbourne
        #postcode: 3004
        #state: Victoria
        country: Australia
  - number: 2
    corresponding: FALSE
    info:
      orgname: Orygen
    address:
     #   street: "35 Poplar Road"
        city: Parkville
        # postcode: 3052
        #state: Victoria
        country: Australia
  - number: 3
    corresponding: FALSE
    info:
      orgdiv: Centre for Youth Mental Health
      orgname: The University of Melbourne
    address:
     #   street: "35 Poplar Road"
        city: Parkville
        # postcode: 3052
    #   state: Victoria
        country: Australia
  - number: 4
    corresponding: FALSE
    info:
#      orgdiv: XXXXXXXXXXX
      orgname: headspace National Youth Mental Health Foundation   
    address:
    #  #   street: "485 La Trobe St"
        city: Melbourne
    #     postcode: 3000
    #  #   state: Victoria
        country: Australia     
        #   - name: Ian B Hickie
  - number: 5
    corresponding: FALSE
    info:
      orgdiv: Brain and Mind Centre, Youth Mental Health & Technology
      orgname: University of Sydney 
    address:
    #  #   street: "70/104 Ballarat Rd"
        city: Camperdown
    #     postcode: 3011
    #  #   state: Victoria
        country: Australia 
        
  - number: 6
    corresponding: FALSE
    info:
      orgdiv: Faculty of Health
      orgname: University of Canberra 
    address:
    #  #   street: "70/104 Ballarat Rd"
        city: Bruce
    #     postcode: 3011
    #  #   state: Victoria
        country: Australia        

keywords:  
  - anxiety
  - AQoL
  - depression
  - psychological distress
  - QALYs
  - utility mapping
  
# pacs: 
#   jel:
#     - "C63"
#     - "C88"
#     - "I10"
#   msc:
#     - "91-08"

# Sample for unstructured abstract 

params:
  endmatter: FALSE 
  X: NULL

abstract: "`r paste0(readLines('../Header/abstract.txt'),collapse=' ')`"

bibliography: RefCopy.bib

header-includes: |
  %% Per the spinger doc, new theorem styles can be included using built in style, 
  %% but it seems the don't work so commented below
  %\theoremstyle{thmstyleone}%
  \newtheorem{theorem}{Theorem}%  meant for continuous numbers
  %%\newtheorem{theorem}{Theorem}[section]% meant for sectionwise numbers
  %% optional argument [theorem] produces theorem numbering sequence instead of independent numbers for Proposition
  \newtheorem{proposition}[theorem]{Proposition}%
  %%\newtheorem{proposition}{Proposition}% to get separate numbers for theorem and proposition etc.

  %% \theoremstyle{thmstyletwo}%
  \theoremstyle{remark}
  \newtheorem{example}{Example}%
  \newtheorem{remark}{Remark}%

  %% \theoremstyle{thmstylethree}%
  \theoremstyle{definition}
  \newtheorem{definition}{Definition}%
  
  \usepackage{float}
  \let\origfigure\figure
  \let\endorigfigure\endfigure
  \renewenvironment{figure}[1][2] {
      \expandafter\origfigure\expandafter[H]
  } {
      \endorigfigure
  }
  \usepackage{lscape}
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  \usepackage[none]{hyphenat}
  \usepackage[export]{adjustbox}
  \usepackage{multirow}
  \usepackage{longtable}
  \usepackage{array}
  \usepackage{wrapfig}
  \usepackage{colortbl}
  \usepackage{booktabs} 
  \usepackage{colortbl}
  \usepackage{pdflscape}
  \usepackage{tabu}
  \usepackage{threeparttable}
  \usepackage[normalem]{ulem}
  \usepackage{threeparttablex}
  \usepackage{makecell}

# output: rticles::springer_article
output: 
  bookdown::pdf_book: 
    base_format: rticles::springer_article
    # includes:
    #   in_header: preamble.tex
    keep_tex: true
    pandoc_args: 
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      out.extra = "")
#library(flextable)# This forces knitr to label all figures.
```

```{r echo = F, warning=FALSE}
library(xtable)
#options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

```{r child="../Child_RMDs/XX_Funs.Rmd", echo=FALSE}
```

```{r echo=FALSE}
print_cohort_table <- function (params_ls, caption_1L_chr, mkdn_tbl_ref_1L_chr)
{
    results_ls <- params_ls$results_ls
    df <- results_ls$tables_ls$participant_descs
    df$variable <- gsub("\\s*\\([^\\)]+\\)", "", df$variable)
    df <- df %>% dplyr::mutate(variable = variable %>% purrr::map_chr(~Hmisc::capitalize(.x)))
    df <- dplyr::filter(df, !df[, 3] == "")
    if (params_ls$output_type_1L_chr == "PDF") {
        df <- df %>% dplyr::mutate_all(~stringr::str_replace(.x,
            "%", "\\\\%") %>% stringr::str_replace(",", "\\\\,"))
    }
    if (params_ls$output_type_1L_chr == "PDF") {
        names(df) <- c("", "", "(N =", paste0(results_ls$cohort_ls$n_inc_1L_dbl,
            ")"), "(N =", paste0(results_ls$cohort_ls$n_fup_1L_dbl,
            ")"))
        df %>% kableExtra::kbl(booktabs = T, caption = knitr::opts_current$get("tab.cap"),
            escape = F) %>% kableExtra::kable_styling() %>% kableExtra::column_spec(3:6,
            width = "6em"#"3em"
            ) %>% kableExtra::column_spec(1, bold = T,
            width = "10em") %>% kableExtra::add_header_above(c(" ",
            " ", Baseline = 2, `Follow-Up` = 2)) %>% kableExtra::collapse_rows(columns = 1)
    }
    else {
        df <- df %>% youthvars::transform_tb_for_merged_col_1(output_type_1L_chr = params_ls$output_type_1L_chr)
        add_to_row_ls <- make_bl_fup_add_to_row_ls(df, n_at_bl_1L_int = results_ls$cohort_ls$n_inc_1L_dbl,
            n_at_fup_1L_int = results_ls$cohort_ls$n_fup_1L_dbl)
        df %>% ready4show::print_table(output_type_1L_chr = params_ls$output_type_1L_chr,
            caption_1L_chr = caption_1L_chr, mkdn_tbl_ref_1L_chr = paste0("tab:",
                knitr::opts_current$get("tab.id")), use_rdocx_1L_lgl = ifelse(params_ls$output_type_1L_chr ==
                "Word", T, F), add_to_row_ls = add_to_row_ls,
            sanitize_fn = force)
    }
}
print_indpnt_predrs_coefs_tbl <- function (params_ls, caption_1L_chr, mkdn_tbl_ref_1L_chr)
{
    results_ls <- params_ls$results_ls
    tb <- results_ls$tables_ls$ind_preds_coefs_tbl %>%
          dplyr::mutate(dplyr::across(starts_with("CI_"),~purrr::map_chr(.x,~ifelse(is.na(.x),.x,paste0("(",.x,")"))))) %>% # New
      transform_nms_in_mdl_tbl(col_nm_1L_chr = "Parameter",
        var_nm_change_lup = results_ls$var_nm_change_lup)
    if (params_ls$output_type_1L_chr == "Word") {
        tb$Parameter <- stringr::str_replace_all(stringr::str_replace_all(stringr::str_replace_all(tb$Parameter,
            "\\\\textbf", ""), "\\{", ""), "\\}", "")
    }
    if (params_ls$output_type_1L_chr == "PDF") {
        tb %>% 
        dplyr::mutate(Parameter = Parameter %>% purrr::map_chr(~stringr::str_replace_all(.x," change"," \\\\(\\\\Delta \\\\)") %>%
                                                                 stringr::str_replace_all(" baseline"," BL") %>%
                                                                 stringr::str_replace_all(" model","") %>%
                                                                 stringr::str_replace_all("Intercept","Intc."))) %>% 
        dplyr::mutate(dplyr::across(.cols = everything(),
                                    ~dplyr::case_when(is.na(.x) ~ "", T ~ .x))) %>% 
        kableExtra::kbl(booktabs = T,
                        caption = knitr::opts_current$get("tab.cap"), 
                        escape = F,
                        longtable = F,#T
                        col.names = c("Parameter",#,#kableExtra::footnote_marker_number(1)
                                      "Est.",#imate
                                      "SE", "CI (95\\%)", "R2", "Sigma", "Est.",#imate
                                      "SE", "CI (95\\%)", "R2", "Sigma")) %>% 
          kableExtra::kable_styling(
            #latex_options = c(#"striped", # New
            #"repeat_header",
            #"hold_position" # NEW
            #)
            ) %>%
          #kableExtra::column_spec(1,width = "8em") %>%
          kableExtra::column_spec(c(4,9),#3:6,
                                  width = "6em"#"3em"
                                  ) %>% 
        kableExtra::row_spec(which(!is.na(tb[,5])), bold = T) %>% 
        kableExtra::add_header_above(parse(text = paste0("c(",
                                                         "\"\\\\\\\\textbf\\\\{Model\\\\}\" = 1", ", ", 
                                                         paste0("\"", results_ls$ttu_lngl_ls$best_mdls_tb[[1, "model_type"]],
                                                                " - ", results_ls$ttu_lngl_ls$best_mdls_tb[[1, "link_and_tfmn_chr"]], "\" = 5"), ", ", 
                                                         paste0("\"", results_ls$ttu_lngl_ls$best_mdls_tb[[2, "model_type"]],
                                                                " - ", results_ls$ttu_lngl_ls$best_mdls_tb[[2,"link_and_tfmn_chr"]], "\" = 5"), ")")) %>% eval(),
                                     escape = FALSE) %>% kableExtra::collapse_rows(columns = 1) %>%
        kableExtra::footnote(general= paste0("Est. - Estimate, ", "SE - Standard Error, ", "CI - Credible Interval, ", 
                                             "Intc. - Intercept, ", "BL - Baseline and ", "$\\\\Delta$ - Change."),
                             number=c(make_scaling_text(results_ls) %>% stringr::str_sub(start = 6)),
                             #threeparttable = T,
                             footnote_as_chunk=TRUE, general_title = " ", escape=FALSE)
        # kableExtra::add_footnote(c("Est. - Estimate", "SE - Standard Error", "CI - Credible Interval", "Intc. - Intercept", "BL - Baseline", "$\\\\Delta$ - Change from baseline"),
        #   # c(make_scaling_text(results_ls),
        #   #                          "Est. - Estimate, SE - Standard Error, CI - Credible Interval, Intc. - Intercept, BL - Baseline, $\\\\Delta$ - Change from baseline."),
        #                          notation = "none",
        #                          escape=FALSE)
            # kableExtra::footnote(general = paste0(make_scaling_text(results_ls),"Est. - Estimate, SE - Standard Error, CI - Credible Interval, Intc. - Intercept, BL - Baseline, \\\\(\\\\Delta \\\\) - Change."),
            #     general_title = " Note.", footnote_as_chunk = TRUE)
    }
    else {
        add_to_row_ls <- NULL
        tb %>% ready4show::print_table(output_type_1L_chr = params_ls$output_type_1L_chr,
            caption_1L_chr = caption_1L_chr, mkdn_tbl_ref_1L_chr = mkdn_tbl_ref_1L_chr,
            use_rdocx_1L_lgl = ifelse(params_ls$output_type_1L_chr ==
                "Word", T, F), add_to_row_ls = add_to_row_ls,
            footnotes_chr = make_scaling_text(results_ls), sanitize_fn = force)
    }
}
```


```{r child="../Child_RMDs/All_Content.Rmd", echo=FALSE, warning=FALSE}
```

