---
output: 
  bookdown::pdf_document2: 
    md_extensions: -auto_identifiers
    template: CUP_TEMPLATE.tex
    citation_package: biblatex
    #base_format: rticles::springer_article
    includes:
      in_header: preamble.tex
    pandoc_args: 
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
    toc: no
    keep_tex: true
#authorship: "`r paste0(paste0(readLines('../Header/Authors.txt')) %>% purrr::map_chr(~paste0(ifelse(.x=="","","/"),stringr::str_sub(.x,start = 2))),"")`"
# authors:
#   - name: Matthew P Hamilton*
#     email: matthew.hamilton@orygen.org.au
#     address: Orygen, Parkville, Australia
#     correspondence: true
#     equal_contributor: "yes"
#   - name: Caroline X Gao
#     address: Orygen, Parkville, Australia, Centre for Youth Mental Health, University of Melbourne, Parkville, Australia and School of Public Health and Preventive Medicine, Monash University, Clayton, Australia
#     equal_contributor: "yes"
#   - name: Kate M Filia
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Jana M Menssink
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Sonia  Sharmin
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Nic Telford
#     address: headspace National Youth Mental Health Foundation, Melbourne, Australia
#   - name: Helen Herrman
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Ian B Hickie
#     address: Brain and Mind Centre, Youth Mental Health & Technology, Faculty of Medicine & Health, The University of Sydney,  Australia
#   - name: Cathrine  Mihalopoulos
#     address: Deakin Health Economics, Institute for Health Transformation, Deakin University, Geelong,  Australia
#   - name: Debra J Rickwood
#     address: Faculty of Health, University of Canberra, Australia and headspace National Youth Mental Health Foundation, Melbourne, Australia
#   - name: Patrick D McGorry
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
#   - name: Sue M Cotton
#     address: Orygen, Parkville, Australia and Centre for Youth Mental Health, University of Melbourne, Parkville, Australia
params:
  endmatter: FALSE    
  X: NULL
abstract: |
    \textit{Background: } Quality Adjusted Life Years (QALYs) are often used in economic evaluations, yet utility weights for deriving them are rarely directly measured in mental health services.
    \textit{Objectives: } We aimed to identify the best mapping models and predictors for adolescent Assessment of Quality of Life - Six Dimensions (AQOL-6D) utility and assess the ability of mapping models to predict longitudinal change.
    \textit{Methods: } We recruited 1107 young people attending Australian primary mental health services, collecting data at two time points, three months apart. Five linear and three generalised linear models were explored to identify the best mapping model. Ten-fold cross-validation using R$^2$, root mean square error (RMSE) and mean absolute error (MAE) were used to compare models and assess predictive ability of six candidate measures of psychological distress, depression and anxiety. Linear / generalised linear mixed effect models were used to construct longitudinal predictive models for AQoL-6D change.
    \textit{Results: } A depression measure (Patient Health Questionnaire-9) was the strongest independent predictor of health utility. Linear regression models with complementary log-log transformation of utility score were the best performing models. Between-person associations were slightly larger than within-person associations for most of the predictors.
    \textit{Conclusions: } Adolescent AQoL-6D utility can be derived from a range of psychological distress, depression and anxiety measures. Mapping models estimated from cross-sectional data can approximate longitudinal change but may slightly bias health utility predictions.
    \textit{Data: } Replication code, detailed results and guidance on how to apply the models produced by this study are available in the online repository: https://doi.org/10.7910/DVN/DKDIB0.
# "`r paste0(readLines('../Header/abstract.txt'), collapse=' ')`"
# graphics: yes
# subtitle: Do you have a subtitle? If so, write it here
title: "`r params$X@title_1L_chr`" 
#titlerunning: Mapping mental health measures to AQoL-6D utility
#authorrunning: Hamilton, Gao, Filia et al.
#journal: Epidemiology and Psychiatric Sciences
#thanks: | 
funding: |
    The study was funded by the National Health and Medical Research Council (NHMRC, APP1076940), Orygen and headspace. 
dataavailability: |
    Dataverse
conflicts: |
    None
keywords: anxiety, AQoL, depression, psychological distress, QALYs, utility mapping
#PACS: 
#- PAC1
#- superPAC

# MSC:
# - MSC code 1
# - MSC code 2
bibliography: RefCopy.bib
#biblio-style: spbasic
#csl: cambridge-university-press-author-date-cambridge-a.csl
# bibstyle options spbasic(default), spphys, spmpsci
# header-includes:
# - \usepackage{booktabs}
# - \usepackage{longtable}
# - \usepackage{array}
# - \usepackage{multirow}
# - \usepackage{wrapfig}
#- \usepackage{float}
# - \usepackage{colortbl}
# - \usepackage{pdflscape}
# - \usepackage{tabu}
# - \usepackage{threeparttable}
# - \usepackage[normalem]{ulem}
# - \usepackage{threeparttablex}
# - \usepackage{makecell}
# - \usepackage{natbib}
---

```{r echo = F, warning=FALSE}
library(xtable)
#options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

```{r child="../Child_RMDs/XX_Funs.Rmd", echo=FALSE}
```

```{r echo=FALSE}
print_cohort_table <- function (params_ls, caption_1L_chr, mkdn_tbl_ref_1L_chr) 
{
    results_ls <- params_ls$results_ls
    df <- results_ls$tables_ls$participant_descs
    df$variable <- gsub("\\s*\\([^\\)]+\\)", "", df$variable)
    df <- df %>% dplyr::mutate(variable = variable %>% purrr::map_chr(~Hmisc::capitalize(.x)))
    df <- dplyr::filter(df, !df[, 3] == "")
    if (params_ls$output_type_1L_chr == "PDF") {
        df <- df %>% dplyr::mutate_all(~stringr::str_replace(.x, 
            "%", "\\\\%") %>% stringr::str_replace(",", "\\\\,"))
    }
    if (params_ls$output_type_1L_chr == "PDF") {
        names(df) <- c("", "", "(N =", paste0(results_ls$cohort_ls$n_inc_1L_dbl, 
            ")"), "(N =", paste0(results_ls$cohort_ls$n_fup_1L_dbl, 
            ")"))
        df %>% kableExtra::kbl(booktabs = T, caption = knitr::opts_current$get("tab.cap"), 
            escape = F) %>% kableExtra::kable_styling() %>% kableExtra::column_spec(3:6, 
            width = "6em"#"3em"
            ) %>% kableExtra::column_spec(1, bold = T, 
            width = "14em") %>% kableExtra::add_header_above(c(" ", 
            " ", Baseline = 2, `Follow-Up` = 2)) %>% kableExtra::collapse_rows(columns = 1)
    }
    else {
        df <- df %>% youthvars::transform_tb_for_merged_col_1(output_type_1L_chr = params_ls$output_type_1L_chr)
        add_to_row_ls <- make_bl_fup_add_to_row_ls(df, n_at_bl_1L_int = results_ls$cohort_ls$n_inc_1L_dbl, 
            n_at_fup_1L_int = results_ls$cohort_ls$n_fup_1L_dbl)
        df %>% ready4show::print_table(output_type_1L_chr = params_ls$output_type_1L_chr, 
            caption_1L_chr = caption_1L_chr, mkdn_tbl_ref_1L_chr = paste0("tab:", 
                knitr::opts_current$get("tab.id")), use_rdocx_1L_lgl = ifelse(params_ls$output_type_1L_chr == 
                "Word", T, F), add_to_row_ls = add_to_row_ls, 
            sanitize_fn = force)
    }
}
print_indpnt_predrs_coefs_tbl <- function (params_ls, caption_1L_chr, mkdn_tbl_ref_1L_chr) 
{
    results_ls <- params_ls$results_ls
    tb <- results_ls$tables_ls$ind_preds_coefs_tbl %>%
          dplyr::mutate(dplyr::across(starts_with("CI_"),~purrr::map_chr(.x,~ifelse(is.na(.x),.x,paste0("(",.x,")"))))) %>% # New
      transform_nms_in_mdl_tbl(col_nm_1L_chr = "Parameter", 
        var_nm_change_lup = results_ls$var_nm_change_lup)
    if (params_ls$output_type_1L_chr == "Word") {
        tb$Parameter <- stringr::str_replace_all(stringr::str_replace_all(stringr::str_replace_all(tb$Parameter, 
            "\\\\textbf", ""), "\\{", ""), "\\}", "")
    }
    if (params_ls$output_type_1L_chr == "PDF") {
        tb %>% dplyr::mutate(dplyr::across(.cols = everything(), 
            ~dplyr::case_when(is.na(.x) ~ "", T ~ .x))) %>% kableExtra::kbl(booktabs = T, 
            caption = knitr::opts_current$get("tab.cap"), escape = F, 
            longtable = F,#T
            col.names = c("Parameter", "Estimate", 
                "SE", "CI (95\\%)", "R2", "Sigma", "Estimate", 
                "SE", "CI (95\\%)", "R2", "Sigma")) %>% kableExtra::kable_styling(
                  #latex_options = c(#"striped", # New
                                                                                                    #"repeat_header",
                                                                                                    #"hold_position" # NEW
                                                                                                    #)
                                                                                  ) %>% 
            kableExtra::column_spec(c(4,9),#3:6, 
                                    width = "6em"#"3em"
                                    ) %>% kableExtra::row_spec(which(!is.na(tb[, 
            5])), bold = T) %>% kableExtra::add_header_above(parse(text = paste0("c(", 
            "\" \"", ", ", paste0("\"", results_ls$ttu_lngl_ls$best_mdls_tb[[1, 
                "model_type"]], " - ", results_ls$ttu_lngl_ls$best_mdls_tb[[1, 
                "link_and_tfmn_chr"]], "\" = 5"), ", ", paste0("\"", 
                results_ls$ttu_lngl_ls$best_mdls_tb[[2, "model_type"]], 
                " - ", results_ls$ttu_lngl_ls$best_mdls_tb[[2, 
                  "link_and_tfmn_chr"]], "\" = 5"), ")")) %>% 
            eval()) %>% kableExtra::collapse_rows(columns = 1) %>% 
            kableExtra::footnote(general = make_scaling_text(results_ls), 
                general_title = " ")
    }
    else {
        add_to_row_ls <- NULL
        tb %>% ready4show::print_table(output_type_1L_chr = params_ls$output_type_1L_chr, 
            caption_1L_chr = caption_1L_chr, mkdn_tbl_ref_1L_chr = mkdn_tbl_ref_1L_chr, 
            use_rdocx_1L_lgl = ifelse(params_ls$output_type_1L_chr == 
                "Word", T, F), add_to_row_ls = add_to_row_ls, 
            footnotes_chr = make_scaling_text(results_ls), sanitize_fn = force)
    }
}
```


```{r child="../Child_RMDs/All_Content.Rmd", echo=FALSE, warning=FALSE}
```
