---
output: 
  bookdown::pdf_book: 
    base_format: rticles::springer_article
    includes:
      in_header: preamble.tex
    pandoc_args: 
      - "--metadata-file=../Header/header_common.yaml"
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
  bookdown::pdf_document2: 
    includes:
      in_header: preamble.tex
    pandoc_args: 
      - "--metadata-file=../Header/header_common.yaml"
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
    toc: no
## CUSTOM_AUTHORS_PLACEHOLDER ##
params:
  X: NULL
abstract: "`r paste0(readLines('../Header/abstract.txt'),collapse=' ')`"
graphics: yes
# subtitle: Do you have a subtitle? If so, write it here
titlerunning: Short form of title (if too long for head)
authorrunning: Short form of author list if too long for running head
thanks: | 
    Grants or other notes about the article that should go on the front 
    page should be placed here. General acknowledgments should be placed at the
    end of the article.

# authors: 
# - name: Äüthör 1
#   address: Department of YYY, University of XXX
#   email: abc@def
#   
# - name: Âuthóř 2
#   address: Department of ZZZ, University of WWW
#   email: djf@wef

#PACS: 
#- PAC1
#- superPAC
    
# MSC:
# - MSC code 1
# - MSC code 2

bibliography: ../Data/bib.bib
biblio-style: spbasic
# bibstyle options spbasic(default), spphys, spmpsci
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
- \usepackage{threeparttablex}
- \usepackage{makecell}
---

```{r echo = F, warning=FALSE}
library(xtable)
#options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```
```{r child="../Child_RMDs/All_Content.Rmd", echo=FALSE, warning=FALSE}
```