---
output: 
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
    pandoc_args: 
#      - "--metadata-file=../Header/header_common.yaml"
      - '--lua-filter=../Filters/scholarly-metadata.lua'
      - '--lua-filter=../Filters/author-info-blocks.lua'
    toc: no
title: "`r params$X@title_1L_chr`" 

authors:
  - firstname: Matthew
    particle: P
    lastname: Hamilton
    email: matthew.hamilton1@monash.edu
    affiliation: [1,2]
    corresponding: TRUE
    equalcont: These authors contributed equally to this work.
  # - prefix: Mr.
    #suffix: III
    #naturename: Poet Laureate
    # degrees: MSc #, PhD

  - firstname: Caroline
    lastname: Gao
    #     email: caroline.gao@orygen.org.au
    affiliation: [2,3,1]
    equalcont: These authors contributed equally to this work.

  - firstname: Kate
    particle: M
    lastname: Filia
    #     email: kate.filia@orygen.org.au
    affiliation: [2,3]

  - firstname: Jana
    particle: M
    lastname: Menssink
    #     email: jana.menssink@orygen.org.au
    affiliation: [2,3]

  - firstname: Sonia
    #particle: M
    lastname: Sharmin
    #     email: jana.menssink@orygen.org.au
    affiliation: [2,3]

  - firstname: Nic
    #particle: M
    lastname: Telford
    #     email: jana.menssink@orygen.org.au
    affiliation: [4]

  - firstname: Helen
    #particle: M
    lastname: Herrman
    #     email: jana.menssink@orygen.org.au
    affiliation: [2,3]

  - firstname: Ian
    particle: B
    lastname: Hickie
    #     email: jana.menssink@orygen.org.au
    affiliation: [5]

  - firstname: Cathrine
    lastname: Mihalopoulos
    #     email: cathy.mihalopoulos@deakin.edu.au
    affiliation: [1]

  - firstname: Debra
    particle: J
    lastname: Rickwood
    #     email: jana.menssink@orygen.org.au
    affiliation: [4,6]

  - firstname: Patrick
    particle: D
    lastname: McGorry
    #     email: pat.mcgorry@orygen.org.au
    affiliation: [2,3]

  - firstname: Sue
    particle: M
    lastname: Cotton
    #     email: sue.cotton@orygen.org.au
    affiliation: [2,3,7,8]

affiliations:
  - number: 1
    corresponding: TRUE
    info:
      orgdiv: School of Public Health and Preventive Medicine
      orgname: Monash University
    address:
        #street: "553 St Kilda Road"
        city: Melbourne
        #postcode: 3004
        #state: Victoria
        country: Australia
  - number: 2
    corresponding: FALSE
    info:
      orgname: Orygen
    address:
     #   street: "35 Poplar Road"
        city: Parkville
        # postcode: 3052
        #state: Victoria
        country: Australia
  - number: 3
    corresponding: FALSE
    info:
      orgdiv: Centre for Youth Mental Health
      orgname: The University of Melbourne
    address:
     #   street: "35 Poplar Road"
        city: Parkville
        # postcode: 3052
    #   state: Victoria
        country: Australia
  - number: 4
    corresponding: FALSE
    info:
#      orgdiv: XXXXXXXXXXX
      orgname: headspace National Youth Mental Health Foundation
    address:
    #  #   street: "485 La Trobe St"
        city: Melbourne
    #     postcode: 3000
    #  #   state: Victoria
        country: Australia
        #   - name: Ian B Hickie
  - number: 5
    corresponding: FALSE
    info:
      orgdiv: Brain and Mind Centre, Youth Mental Health & Technology
      orgname: University of Sydney
    address:
    #  #   street: "70/104 Ballarat Rd"
        city: Camperdown
    #     postcode: 3011
    #  #   state: Victoria
        country: Australia

  - number: 6
    corresponding: FALSE
    info:
      orgdiv: Faculty of Health
      orgname: University of Canberra
    address:
    #  #   street: "70/104 Ballarat Rd"
        city: Bruce
    #     postcode: 3011
    #  #   state: Victoria
        country: Australia

  - number: 7
    corresponding: FALSE
    info:
      orgdiv: School of Psychological Sciences
      orgname: Monash University
    address:
        city: Melbourne
        country: Australia

  - number: 8
    corresponding: FALSE
    info:
      orgdiv: Turner Institute of Brain and Mental Health
      orgname: Monash University
    address:
        city: Melbourne
        country: Australia

params:
  X: NULL
graphics: yes
subtitle: Online Supplement
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
- \usepackage{threeparttablex}
- \usepackage{makecell}
---

```{r echo = F, warning=FALSE}
library(xtable)
library(ready4show)
#options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```
```{r echo = F}
# if(!exists("params_ls")){
  X <- params$X
  params_ls<- list(figures_in_body_lgl = X@figures_in_body_lgl,
                   output_type_1L_chr = X@outp_formats_chr[1],
                   results_ls = X@b_SpecificResults@a_SpecificShareable@shareable_outp_ls$results_ls,
                   tables_in_body_lgl = X@tables_in_body_lgl)
  results_ls <- params_ls$results_ls
# }
```

\appendix
\counterwithin{figure}{section}
\counterwithin{table}{section}

\newpage

# Additional tables

```{r child="../Child_RMDs/TA_Body.Rmd", echo=FALSE, warning=FALSE}
```

\newpage

# Additional figures

```{r child="../Child_RMDs/TA_Figures.Rmd", echo=FALSE, warning=FALSE}
```