library(ready4)
#path_1L_chr <- "SPECIFY PATH ENDING IN '/' "
A <- readRDS(paste0(path_1L_chr,"A.RDS")) # Read in results
A@d_TTUReports@a_TTUSynopsis@a_Ready4showPaths@outp_data_dir_1L_chr <- paste0(path_1L_chr,"Real") # Update relative path to raw output
A@d_TTUReports@a_TTUSynopsis@abstract_args_ls$abstract_ls <- list(Objective = "We aimed to identify the best models and predictors to map psychological measures to adolescent Assessment of Quality of Life - Six Dimensions (AQOL-6D) utility and assess the ability of these models to predict longitudinal utility change.", 
                                                                  Methods = "We recruited 1107 young people attending Australian primary mental health services, collecting data at two time points, three months apart. Five linear and three generalised linear models were explored to identify the best mapping model. Ten-fold cross-validation using R^2, root mean square error (RMSE) and mean absolute error (MAE) were used to compare models and assess predictive ability of six candidate measures of psychological distress (Kessler Psychological Distress Scale), depression (Patient Health Questionnaire-9 and Behavioural Activation for Depression Scale) and anxiety (Generalised Anxiety Disorder Scale, Screen for Child Anxiety Related Disorders and Overall Anxiety Severity and Impairment Scale). Linear / generalised linear mixed effect models were used to construct longitudinal predictive models.", 
                                                                  Results = "A depression measure (Patient Health Questionnaire-9) was the strongest independent predictor of health utility. Linear regression models with complementary log-log transformation of utility score were the best performing models. Between-person associations were slightly larger than within-person associations for most of the predictors.", 
                                                                  Conclusions = "Adolescent AQoL-6D utility can be derived from a range of psychological distress, depression and anxiety measures. Mapping models estimated from cross-sectional data can approximate longitudinal change but may slightly bias health utility predictions.  The mapping models we have created can facilitate economic evaluations of youth mental health services using cost-utility analyses.")
A@d_TTUReports@a_TTUSynopsis@title_1L_chr <- "Mapping psychological measures to adolescent AQoL-6D utility using data from young people attending primary mental health services"
#dir.create(paste0(A@d_TTUReports@a_TTUSynopsis@a_Ready4showPaths@outp_data_dir_1L_chr,"/Markdown/Manuscript_Submission"))
#file.copy(list.files(getwd()),paste0(A@d_TTUReports@a_TTUSynopsis@a_Ready4showPaths@outp_data_dir_1L_chr,"/Markdown/Manuscript_Submission"), recursive = T)
setwd(paste0(A@d_TTUReports@a_TTUSynopsis@a_Ready4showPaths@outp_data_dir_1L_chr,"/Markdown/Manuscript_Submission/Parent_PDF"))
authorSlot(A, "d_TTUReports", what_1L_chr = "Manuscript_Submission", download_tmpl_1L_lgl = F)