---
title: "MS_Discussion"
output: html_document
---

Our study was motivated by a desire to incorporate QALY outcomes in a simulation model of primary youth mental health services that we are developing. However, MAUIs are rarely included in routine data collection in clinical mental health services and direct measures of health utility may not exist in many relevant datasets. This gap means that it can be difficult to derive much economic insight from the often-rich outcome data that is collected in administrative and treatment evaluation datasets. Utility mapping is a commonly adopted solution to such problems, but existing mapping algorithms may not appropriately predict longitudinal change in utility weights in help-seeking young people. Our study addresses this important gap and is the first to evaluate longitudinal mapping ability between a wide range of affective symptom measurements and health utility in a cohort of help seeking young people.

Although there is encouraging evidence about the quality, effectiveness and cost-effectiveness of youth mental health service innovations worldwide [26][27], the public health and economic returns from systemic reforms to support better mental health in young people still needs to be better understood [28]. Our study contributes to this goal by developing tools that can extract additional economic insights into existing mental health datasets by facilitating derivation of QALYs from measures commonly collected in youth mental health services.

Our mapping algorithms enable greater use of cost-utility analyses (CUAs) in studies using youth mental health data collections. Unlike alternative economic evaluation types (e.g., Cost Consequence Analysis and Cost-Effectiveness Analysis using measures other than health utility) CUAs have commonly understood willingness to pay thresholds for outcomes and facilitate comparison of the value for money claims of interventions from different illness groups. In practical terms, CUAs can help a decision-maker assess the competing economic claims of an intervention for depression compared to an intervention in anxiety or determine whether it may be efficient to fund expanded access to specified mental health services by redirecting parts of the general health budget.

As many youth mental health services routinely collect data on at least one of our six candidate predictors and the measure of functioning (SOFAS) included in our models, the mapping algorithms we developed in this study may have widespread applicability. Importantly, our mapping algorithms were developed in a clinical sample of 12-25 year-olds, using adolescent AQoL-6D weights. We were able to independently predict adolescent AQoL-6D from each of the six candidate measures we assessed, with PHQ-9 having the best predictive performance. Predictive performance was improved when adding SOFAS as an additional predictor or confound to each model; SOFAS also performed well as an independent predictor. These results may be useful for service system planners in helping to prioritise which measures should be included in routine data collection. Although direct measurement of health utility with measures such as the ReQoL [29] may be feasible in some mental health services, relying on clinical measures that can also map to health utility may be an attractive alternative.

A key feature of QALYs is their longitudinal dimension - health utilities are weighted and aggregated based on the time spent in varying health states. Our results suggest that psychological distress, depression and anxiety measurements explain the variations of health utility and cross-sectional variations can be used to approximate the longitudinal change in this cohort. However, a finding of our study is that, for psychological distress and depression measures at least, mapping algorithms developed from cross-sectional data may slightly over-estimate these changes, introducing bias into QALY predictions (overestimating QALYs for populations whose health utility improves over time, underestimating QALYS for those with deteriorating mental health). 

Key strengths of our study include the novelty of our clinical youth mental health study sample, the use of clinically relevant and frequently collected outcome measures as predictors, the appropriateness and range of statistical methods deployed, the comparison of within-person and between-person differences in health utility weight predictions and highly replicable, publicly disseminated study algorithms. We acknowledge limitations that our data pertained to a single country, and we explored only one MAUI-derived utility weight. We did not examine some potential predictors that may be more common in some mental health services (for example we explored K6, as opposed to the expanded, and commonly used measure, the K10). We also did not develop age-group specific models which would be a potentially useful extension of this work. 

However, using utility weight input data derived from the same country as that to which an analysis pertains may be relatively unimportant [30], particularly when the MAUI is well suited to the relevant health condition (as is the case with AQoL and mental health [9]). Furthermore, our R packages should help make it relatively straightforward for others to replicate and extend our study algorithm in different samples (non-Australian, non-clinical and/or non-youth populations) and generalise our methods to developing mapping algorithms that use different predictors (other clinical, functioning and demographic measures) and other utility measures (e.g., EQ-5D). Clinical trial datasets, which now usually collect MAUIs, could provide rich opportunities for applying our algorithm to develop and test new mapping algorithms.

By distributing study outputs as freely available open science resources we hope to make it easier to access and appropriately and consistently apply study findings. Open science resources also provide a valuable opportunity for other researchers to contribute refinements and extensions so that the usefulness of our study algorithm improves with time.


