---
title: "MS_Intro_Long"
author: "Matthew Hamilton"
date: "13/10/2020"
output: html_document
---

Quality adjusted life years (QALYs) are indices of outcome that inform public health policy in many countries [@RN3417]. The “quality” in QALYs is measured via the use of multi-attribute utility instruments (MAUIs), where domains of quality of life measured by a questionnaire are weighted using people’s preferences [@RN3418]. This approach produces a single health utility value for each individual at each measured health state, anchored on a scale where 0 represents a state equivalent to death and 1 represents perfect health. Health utilities can be converted to QALYs by weighting the duration (the “years” part of QALYs) each individual spends in each health state.

One of the main uses of QALYs is as the measure of benefit in Cost-Utility Analyses (CUAs).  Compared to economic evaluations that use other outcome measures, CUAs have a number of advantages. The generic nature of the health outcomes measured by QALYs facilitate comparisons of the value-for-money claims of interventions for different health conditions. CUAs integrate information on multiple domains relevant to health policymakers – including the durability of changes in health outcomes and the importance of those outcomes to a population.  The existence of well understood policymaker willingness-to-pay thresholds for QALYs make it easier to draw value-for-money conclusions from the results of CUAs. 

MAUIs are regularly used in research studies such as clinical trials and epidemiological surveys, but rarely feature in routine data collection by health services. As evaluators of health services often rely on routinely collected patient outcome data, the absence of directly measured health utility can be a significant barrier to undertaking CUAs. Mapping analysis has been developed to overcome this barrier by predicting health utility from standard health status measurements [@RN7; @Wailoo2017]. Mapping analysis has been applied in many domains of healthcare, including mental health. MAUIs such as the Assessment of Quality of Life – Eight Dimensions (AQoL-8D [@Richardson2014]) have been shown to be sensitive to psychological measures [@RN6] and can be mapped to [@RN4] using measures of psychological distress (measured using Kessler Psychological Distress Scale – 10 items, K10 [@RN16]) and depression and anxiety symptoms (measured using Depression, Anxiety, and Stress Scale – 21 items, DASS-21 [@henry_2005]). Measures of anxiety (Generalised Anxiety Disorder Scale (GAD-7; [@RN13]) and depression (Patient Health Questionnaire-9 (PHQ-9; [@RN11]) have recently been used to map to other MAUIs [@franklin2023enabling].  However, it is unclear which mental health measures are the most predictive of health utility and existing algorithms developed for adult [@RN4] or child [@pmid23943259] general populations are of questionable appropriateness for predicting health utility in clinical youth mental health samples. 

Currently available mapping algorithms are largely derived from cross-sectional data and assume that the associations between psychological measurements and health utility are time-invariant. Therefore, the between-person association (variations in mental health symptoms associated with variations in health utility observed cross-sectionally in a population) can be applied to estimate the within-person association (changes in mental health symptoms associated with changes in health utility over time). However, this time invariant assumption may not be true (for example, health utility measures may be less sensitive to change compared with measures of mental health symptoms).

