---
title: "TTU"
author: "Matthew Hamilton"
date: "26/01/2021"
output: html_document
---

## Regression model performance 
<!-- Table start -->The 10-fold cross-validated model fitting index from mapping models using `r get_ordered_sngl_csnl_mdls(results_ls, select_int = 1)` are reported in Online Resource `r ifelse(params_ls$output_type_1L_chr=="Word","","Table")` A.1. Both training and testing R^2^, RMSE and MAE were comparable between the GLM and beta regression models.  OLS model with no transformation or clog-log transformation, GLM with Gaussian distribution and log link and beta regression with logit or cloglog link were found amongst best preforming models. As there were convergence issues with beta regression models, these models were not considered further as they do not show major advantages in predictive performance.   

Model diagnoses (such as heteroscedasticity, residual normality) suggested better model fit of the clog-log transformed OLS model, as the distribution clog-log transformed utility are closest to normal distribution among all transformation methods. Another benefit of the clog-log transformed model is that the predicted utility score will be constrained with an upper bound of 1, thus preventing out of range prediction. Therefore, OLS with clog-log transformation was chosen as the best model for further evaluation As the GLM with Gaussian distribution and log link is also commonly used in mapping studies [@Mukuria2019], it is also included to provide easy comparisons with other published work. 

PHQ9 had the highest predictive ability followed by OASIS, BADS, GAD7 and K6 (Online Resource `r paste0(ifelse(params_ls$output_type_1L_chr=="Word","","Table "), "A.2 ")` ). SCARED had the least predictive capability. The confounding effect of other participant characteristics were also evaluated when using the candidate predictors in predicting utility score. Using the baseline data, SOFAS was found to independently predict utility scores in models for all six candidate predictors (*p<0.005*). Sex at birth was found to be a confounder for the K6 model (*p<0.01*). A few other confounders, including primary diagnosis, clinical staging and age were identified as weakly associated with utility in mapping models using anxiety and depression measurements other than PHQ-9. Considering many of these factors are unlikely to change over three months, they were not evaluated in the mixed effect models.

```{r echo = F, results='asis'}
# paste0(ifelse(params_ls$output_type_1L_chr=="Word","","Table "),
#        "\\@ref(tab:tenfoldglmtb)). "
#        ) %>% writeLines()
```
