---
title: "MA_Results"
author: "Matthew Hamilton"
date: "13/10/2020"
output: html_document
---
```{r echo = F}
library(officedown)
library(specific)
```
```{r}
print_covar_ttu_tbls <- function(params_ls, # Rename and generalise from TTU
                                 caption_1L_chr,
                                 table_1L_chr,
                                 ref_1L_int = 1){
  results_ls <- params_ls$results_ls
  df <- results_ls$tables_ls %>%
    purrr::pluck(paste0("mdl_type_",ref_1L_int,"_covar_mdls_tb"))
  if(!is.null(df)){
    df <- df %>%
      transform_nms_in_mdl_tbl(col_nm_1L_chr = "Parameter",
                               var_nm_change_lup = results_ls$var_nm_change_lup) %>%
      dplyr::mutate(Parameter = Parameter %>% purrr::map_chr(~stringr::str_replace_all(.x,"_"," ")))
    df %>%
      print_lngl_ttu_tbls(caption_1L_chr = caption_1L_chr,
                          params_ls = params_ls,
                          ref_1L_int = ref_1L_int,
                          table_1L_chr = table_1L_chr)
  }
}
print_lngl_ttu_tbls <- function(table_df, # Rename and generalise from TTU
                                params_ls,
                                caption_1L_chr,
                                table_1L_chr,
                                column_1_width_1L_chr = "25em",
                                ref_1L_int = 1){
  results_ls <- params_ls$results_ls
  if(params_ls$output_type_1L_chr == "PDF"){
    add_to_row_ls <- list()
    add_to_row_ls$pos <- list(0, nrow(table_df))
    add_to_row_ls$command <- c("Parameter & Estimate	& SE	& 95CI & R2	& Sigma\\\\\n",
                               paste0("\\hline\n",
                                      "{\\footnotesize ",
                                      make_scaling_text(results_ls,
                                                        table_1L_chr = knitr::opts_current$get("tab.id")),
                                      "}\n"))
    table_df$Parameter <- table_df$Parameter %>% purrr::map_chr(~ifelse(endsWith(.x,
                                                                                 " model"),
                                                                        paste0("\\textbf{",.x,"}"),.x))
  }else{
    add_to_row_ls <- NULL
  }
  if(params_ls$output_type_1L_chr == "PDF"){
    table_df %>%
      dplyr::mutate(dplyr::across(.cols = everything(),
                                  ~ dplyr::case_when(is.na(.x) ~ "",
                                                     T ~ .x))) %>%
      kableExtra::kbl(booktabs = T,
                      caption = knitr::opts_current$get("tab.cap"),
                      escape = F,
                      longtable = T,
                      col.names = c("Parameter", "Estimate",	"SE",	"CI (95\\%)", "R2", "Sigma")) %>%
      kableExtra::kable_styling(latex_options = c("repeat_header"),
                                full_width = F) %>%
      kableExtra::column_spec(1, width = column_1_width_1L_chr) %>%
      kableExtra::row_spec(which(!is.na(table_df[,5])), bold = T) %>%
      kableExtra::collapse_rows(columns = 1) %>%
      kableExtra::footnote(general = make_scaling_text(results_ls,
                                                        table_1L_chr = table_1L_chr),
                           general_title = " ")
  }else{
    table_df %>%
      ready4show::print_table(output_type_1L_chr = params_ls$output_type_1L_chr,
                              caption_1L_chr = caption_1L_chr,
                              mkdn_tbl_ref_1L_chr = paste0("tab:",table_1L_chr),
                              use_rdocx_1L_lgl = ifelse(params_ls$output_type_1L_chr=="Word",T,F),
                              add_to_row_ls = add_to_row_ls,
                              footnotes_chr = make_scaling_text(results_ls,
                                                                table_1L_chr = table_1L_chr),
                              hline_after_ls = c(-1,0),
                              sanitize_fn = force)
  }
}
print_ten_folds_tbl <- function(params_ls,
                                caption_1L_chr,
                                mkdn_tbl_ref_1L_chr,
                                column_1_width_1L_chr = "20em",
                                ref_1L_int = 1){
  results_ls <- params_ls$results_ls
  if(ref_1L_int ==1){
    df <- results_ls$tables_ls$tenf_sngl_predr_tb %>%
      dplyr::mutate(Model = gsub('"', '', Model)) %>%
      dplyr::mutate(dplyr::across(.cols = dplyr::everything(), ~ .x %>%
                                    stringr::str_replace_all("  NA", NA_character_)))  %>%
      dplyr::mutate(Model = Model %>% purrr::map_chr(~Hmisc::capitalize(.x)))
  }else{
    df <- results_ls$tables_ls$tenf_prefd_mdl_tb
    df$Predictor <- df$Predictor %>% transform_names(rename_lup = results_ls$var_nm_change_lup)
  }
  if(params_ls$output_type_1L_chr == "PDF"){
    if(ref_1L_int ==1){
      df$Model <- df$Model %>% purrr::map_chr(~ifelse(.x %in% c("GLM","OLS"),
                                                      paste0("\\textbf{",
                                                             .x,
                                                             "}"),.x))
    }else{
      df$Predictor <- df$Predictor %>% purrr::map_chr(~paste0("\\textbf{",.x,"}"))
    }
        df %>%
          dplyr::mutate(dplyr::across(.cols = everything(),
                                  ~ dplyr::case_when(is.na(.x) ~ "",
                                                     T ~ .x))) %>%
          kableExtra::kbl(booktabs = T,
                          caption = knitr::opts_current$get("tab.cap"),
                          escape = F,
                          longtable = T,
                          col.names = c("Model", "R2",	"RMSE",	"MAE", "R2", "RMSE", "MAE")) %>%
          kableExtra::kable_styling(latex_options = c("repeat_header"),
                                    full_width = F) %>%
          kableExtra::column_spec(1, bold = T, width = column_1_width_1L_chr) %>%
          kableExtra::add_header_above(parse(text=paste0("c(",
                                                         "\" \"",
                                                         ", ",
                                                         paste0("\"",
                                                                "Training model fit",
                                                                "\" = 3"),
                                                         ", ",
                                                         paste0("\"",
                                                                "Testing model fit",
                                                                "\" = 3"),
                                                         ")"
                                                         )) %>% eval()
                                       ) %>%
          kableExtra::collapse_rows(columns = 1) %>%      
          kableExtra::footnote(general = "Results are averaged over ten folds. RMSE: Root Mean Squared Error; MAE: Mean Absolute Error",
                           general_title = " ")
    
  }else{
    add_to_row_ls <- NULL
      df %>%
    ready4show::print_table(output_type_1L_chr = params_ls$output_type_1L_chr,
                            caption_1L_chr = caption_1L_chr,
                            mkdn_tbl_ref_1L_chr = mkdn_tbl_ref_1L_chr,
                            use_rdocx_1L_lgl = ifelse(params_ls$output_type_1L_chr=="Word",T,F),
                            add_to_row_ls = add_to_row_ls,
                            hline_after_ls = c(-1,0),
                            sanitize_fn = force)
  }
}
# get_pkg_citn <- function(pkg_nm_1L_chr){
#   citn_chr <- suppressWarnings(citation(pkg_nm_1L_chr)) %>% capture.output()
#   start_idx_1L_int <- 4
#   end_idx_1L_int <- which(citn_chr== "")[which(which(citn_chr== "")>start_idx_1L_int)[1]]-1
#   citn_1L_chr<- citn_chr[start_idx_1L_int:end_idx_1L_int] %>% paste0(collapse = "")
#   return(citn_1L_chr)
# }
```

